---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-api
  labels:
    app: bookapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp-api
  template:
    metadata:
      labels:
        app: bookapp-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: api
        image: shivamsoni1995/bookapp-api
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-api-service
spec:
  selector:
    app: bookapp-api
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-ui
  labels:
    app: bookapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp-ui
  template:
    metadata:
      labels:
        app: bookapp-ui
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: ui
        image: shivamsoni1995/bookapp-ui
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-ui-service
spec:
  selector:
    app: bookapp-ui
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: bookapp-api-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookapp-ui-service
            port:
              number: 3000
